[runtime]
log_level = "WARNING"
dlthub_telemetry = true

[normalize]
loader_file_format = "parquet"

[destination.filesystem]
loader_file_format = "parquet"

[destination.bigquery]
loader_file_format = "parquet"
