name: 'dwh_in_a_box'
version: '1.0.0'
config-version: 2

profile: 'dwh-in-a-box-profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwh_in_a_box:
    materialized: table
    intermediate:
      +materialized: view
    mart:
      +materialized: table
      +tags: ['mart', 'reporting']