name: 'dwh_on_a_lake'
version: '1.0.0'
config-version: 2

profile: 'dwh-on-a-lake-profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ setup_gcs_credentials() }}"

models:
  dwh_on_a_lake:
    +materialized: table
    intermediate:
      +materialized: view
    mart:
      +materialized: table
      +tags: ['mart', 'reporting']