dwh-on-a-lake-profile:
  outputs:
    dev:
      type: duckdb
      extensions:
        - parquet
      path: /tmp/newsapi_articles.duckdb
      schema: main
      threads: 4
    prod:
      type: duckdb
      extensions:
        - parquet
      path: "md:dwh_on_a_lake?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: main
      threads: 4
  target: dev
